<!DOCTYPE html>
<html>
<head>
<title>SiteWhere - <c:out value="${swtitle}"/></title>
<script src="${pageContext.request.contextPath}/scripts/jquery.js"></script>
<script src="${pageContext.request.contextPath}/scripts/kendo.web.min.js"></script>
<script src="${pageContext.request.contextPath}/scripts/sitewhere.js"></script>
<link href="${pageContext.request.contextPath}/css/kendo.common.min.css" rel="stylesheet" />
<link href="${pageContext.request.contextPath}/css/kendo.bootstrap.min.css" rel="stylesheet" />
<link href="${pageContext.request.contextPath}/css/bootstrap.min.css" rel="stylesheet" media="screen">
<link href="${pageContext.request.contextPath}/css/sitewhere.css" rel="stylesheet" />
</head>
<body>
	<div class="k-content container">
		<div class="row">
			<div class="span6">
				<h1>SiteWhere <small>M2M in the Cloud</small></h1>
			</div>   
			<div class="span6">
				<ul class="nav nav-pills pull-right" style="margin-bottom: 0px; margin-top: 15px;">
					<li class="active"><a href="#">Devices</a></li>
					<li><a href="#">Administration</a></li>
				</ul>
			</div>
		</div>
