<!-- Hardware asset template -->
<script type="text/x-kendo-tmpl" id="hardwareAsset">
	<div class="hwasset">
		<img src="#:imageUrl#"/>
		<p><b>#:name#</b></p>
		<p>#:description#</p>
	</div>
</script>

<!-- Person asset template -->
<script type="text/x-kendo-tmpl" id="personAsset">
	<div class="hwasset">
		<img src="#:photoUrl#"/>
		<p><b>#:name#</b></p>
		<p><i>#:emailAddress#</i></p>
	</div>
</script>
